add db table: building - handle all changes
cergina/SecureDataCollector pull request #41
Opened 2021-04-20 15:08 UTC by ludko

schema v18
obrazovky vyzera funguju, no potreboval by som poriadnu review lebo nie je v ludskych silach zvazit vsetky mozni co sa mohlo pokazit.
Kludne mi dajte potom dorobit

2021-04-20 20:28 UTC, cergina commented on src/main/java/Model/Database/Interaction/I_Building.java
> +            throw new SQLException("Given attribute I_Building is not ok for database enter");
Given attribute T_Building is not ok for database enter

2021-04-20 20:32 UTC, cergina commented on src/main/java/Model/Database/Interaction/I_CentralUnit.java
> +        boolean rule = buildingID > 0;
konvencia je, ze buildingRule, aj ked je len jedna, nech je to jasne plz

2021-04-20 20:32 UTC, cergina commented on src/main/java/Model/Database/Interaction/I_Flat.java
> +        boolean rule = buildingId > 0;
opat buildingRule

2021-04-20 20:38 UTC, xcipelova commented on src/main/java/Model/Web/Specific/RequestForConsumption.java
> +public class RequestForConsumption extends PrettyObject { // TODO ma byt pouzity normalne controller model, kde sa pouzije iba jeden atribut, nie zbytocne vytvarat dalsi modelovy objekt, model neznam
sice je to model navyse, ale je to takto prehladnejsie pre programatora

2021-04-20 20:38 UTC, cergina commented on src/main/webapp/WEB-INF/templates/fragments/flat_table.html
> +            <div class="st_column _uid" th:text="${flat.apartmentNO}"></div> // TODO tu je nejaka chyba tie class s _ nesedia neviem co to ma robit
komentar dat na <!-- ak tak nieco --> (lebo potom sa ten text zobrazuje vo flate

2021-04-20 20:40 UTC, cergina commented on src/main/webapp/WEB-INF/templates/fragments/flat_table.html
> +            <div class="st_column _dip" th:text="${flat.buildingId}"></div>
asi by to malo byt tak, ze _index-short, _index-long, _index-general, ... tak ako su v css tieto triedy spomenute akoze a vyuzivane inde. ide o to, ze tieto _uid _dip tu kontroluju minimalnu dlzku tychto textboxov co je dolezite pre zarovnanie aj s hore uvedenymi vecami v stlpcoch

2021-04-20 20:40 UTC, cergina commented on src/main/webapp/WEB-INF/templates/fragments/flat_table.html
> -            <div class="st_column _uid" th:text="${flat.apartmentNO}"></div>
asi by to malo byt tak, ze _index-short, _index-long, _index-general, ... tak ako su v css tieto triedy spomenute akoze a vyuzivane inde. ide o to, ze tieto _uid _dip tu kontroluju minimalnu dlzku tychto textboxov co je dolezite pre zarovnanie aj s hore uvedenymi vecami v datach

2021-04-20 20:45 UTC, cergina commented on src/main/webapp/WEB-INF/templates/fragments/flat_table.html
>              <div class="st_column _link flat_link" th:text="${flat.id}" th:if="${isAdmin}"></div>
Tento konkretny je _link a tu ma byt link neviem, ci je ok tu zobrazovat flat.id

2021-04-20 20:46 UTC, cergina commented on src/main/webapp/WEB-INF/templates/fragments/flat_table.html
> +            <div class="st_column _dip" th:text="${flat.buildingId}"></div>
plus este buildingId ak sa tu zobrazuje tak hore v nazve je address

2021-04-20 20:52 UTC, cergina requested changes
V ConfigClasse zmenit sql verziu na 18, takisto v sqlku vytvaracom, pozmenit veci a urcite subor GlassFish_5_0_1.xml nepushuj ako zmeneny, pretoze ja napr vyuzivam novsiu javu uz lebo mi inak nejde projekt a toto ma nuti si to manualne potom menit ked ti to testujem, ale grafy po vlozeni insertov vyzeraju OK, len teda tie spomenute zmeny. Rada, ak nechces pushovat svoju zmenenu konfiguraciu glassfishu tak si ju move to another changelist , napriklad ten tvoj co sa ku mne dostal ze "Moje"

2021-04-21 04:57 UTC, ludko commented on src/main/webapp/WEB-INF/templates/fragments/flat_table.html
> +            <div class="st_column _dip" th:text="${flat.buildingId}"></div>
ale nema to byt ze _apartmentno? ved uid dip su stlpce v inej tabulke

2021-04-21 05:01 UTC, ludko commented on src/main/java/Model/Web/Specific/RequestForConsumption.java
> +public class RequestForConsumption extends PrettyObject { // TODO ma byt pouzity normalne controller model, kde sa pouzije iba jeden atribut, nie zbytocne vytvarat dalsi modelovy objekt, model neznam
no tento nazor nezdielam

2021-04-21 05:03 UTC, ludko commented
> V ConfigClasse zmenit sql verziu na 18, takisto v sqlku vytvaracom, pozmenit veci a urcite subor GlassFish_5_0_1.xml nepushuj ako zmeneny, pretoze ja napr vyuzivam novsiu javu uz lebo mi inak nejde projekt a toto ma nuti si to manualne potom menit ked ti to testujem, ale grafy po vlozeni insertov vyzeraju OK, len teda tie spomenute zmeny. Rada, ak nechces pushovat svoju zmenenu konfiguraciu glassfishu tak si ju move to another changelist , napriklad ten tvoj co sa ku mne dostal ze "Moje"

V tomto commite ale nebol .xml ci?

2021-04-21 05:09 UTC, ludko commented on src/main/webapp/WEB-INF/templates/fragments/flat_table.html
> -            <div class="st_column _uid" th:text="${flat.apartmentNO}"></div>
duplikat

2021-04-21 05:10 UTC, ludko commented on src/main/webapp/WEB-INF/templates/fragments/flat_table.html
>              <div class="st_column _link flat_link" th:text="${flat.id}" th:if="${isAdmin}"></div>
ono sa nezobrazi finalne len sa tam prida a po nacitani s z toho urobi link

2021-04-21 07:50 UTC, cergina commented on src/main/webapp/WEB-INF/templates/fragments/flat_table.html
> +            <div class="st_column _dip" th:text="${flat.buildingId}"></div>
Ano a prave preto aby sme nevyuzivali tieto veci pre kazdy stlpec je v css take, že _index-short, _index-general, _index-long v zavislosti od toho že koľko miesta to potrebuje.

2021-04-21 07:51 UTC, ludko commented on src/main/webapp/WEB-INF/templates/fragments/flat_table.html
> +            <div class="st_column _dip" th:text="${flat.buildingId}"></div>
nerozumiem, povedz proste ako to zmenit

2021-04-21 07:53 UTC, cergina commented on src/main/webapp/WEB-INF/templates/fragments/flat_table.html
>              <div class="st_column _link flat_link" th:text="${flat.id}" th:if="${isAdmin}"></div>
hej, potom je to ok

2021-04-21 07:54 UTC, cergina requested changes
tak uz len ta drobnost

2021-04-21 08:11 UTC, cergina commented on src/main/webapp/WEB-INF/templates/fragments/flat_table.html
> +            <div class="st_column _dip" th:text="${flat.buildingId}"></div>
<div class="st_column _index-long">Apartment Number</div>
<div class="st_column _index-short">BuildingId</div>

a podobne tie spodne k nim long a short tiez, lebo toto hore su nazvy stlpcov

2021-04-21 08:13 UTC, ludko commented on src/main/webapp/WEB-INF/templates/fragments/flat_table.html
> +            <div class="st_column _dip" th:text="${flat.buildingId}"></div>
ci ze namiesto _uid a _dip _link mam dat _index-short ?

2021-04-21 08:15 UTC, cergina commented on src/main/webapp/WEB-INF/templates/fragments/flat_table.html
> +            <div class="st_column _dip" th:text="${flat.buildingId}"></div>
_link zachovaj lebo to je naozaj link, iba tie _uid a _dip nahradit. S tym, ze ApartmentNo musi byt _index-long, lebo  ten popis moze byt fakt dlhy a treba aby bol zarovnany s dlzkou stlpca aj obsah

2021-04-21 08:16 UTC, cergina commented on src/main/webapp/WEB-INF/templates/fragments/flat_table.html
> +            <div class="st_column _dip" th:text="${flat.buildingId}"></div>
blbe je ze ja som sem dal celu ukazku toho jak to zmenit... ale git mi to nezozral to html a prepisal to len na text

2021-04-21 08:19 UTC, ludko commented
> V ConfigClasse zmenit sql verziu na 18, takisto v sqlku vytvaracom, pozmenit veci a urcite subor GlassFish_5_0_1.xml nepushuj ako zmeneny, pretoze ja napr vyuzivam novsiu javu uz lebo mi inak nejde projekt a toto ma nuti si to manualne potom menit ked ti to testujem, ale grafy po vlozeni insertov vyzeraju OK, len teda tie spomenute zmeny. Rada, ak nechces pushovat svoju zmenenu konfiguraciu glassfishu tak si ju move to another changelist , napriklad ten tvoj co sa ku mne dostal ze "Moje"

este mi povedz ako mozes vyvyjat na inej Jave :D :D

2021-04-21 08:34 UTC, merged