Unify coding style
cergina/SecureDataCollector pull request #50
Opened 2021-04-27 13:48 UTC by ludko

2021-04-27 13:52 UTC, ludko commented
no povedz co myslis. Z mojej strany package Scenario moze uz takto zostat, jedina vec co este snad, ale to som nechcel bez teba menit su tie metody kt kopiruju vlastne iba to iste co je na vrstve I_*
ako napr:

```
private T_ControllerUnit get_TControllerUnit_ById(@NotNull final Integer id) {
        T_ControllerUnit t = null;

        try {
            t = InteractionWithDatabase.retrieve(db.getConn(), db.getPs(), db.getRs(), DbEntity.ReturnUnusable(T_ControllerUnit.class), id);
        } catch (SQLException sqle) {
            CustomLogs.Error(sqle.getMessage());
        }

        return t;
}
```

alebo

```
private T_Flat get_TFlat_ById(@NotNull final Integer id) {
        T_Flat t = null;

        try {
            t = InteractionWithDatabase.retrieve(db.getConn(), db.getPs(), db.getRs(), DbEntity.ReturnUnusable(T_Flat.class), id);
        } catch (SQLException sqle) {
            CustomLogs.Error(sqle.getMessage());
        }

        return t;
    }
```

atd

je vlastne 1) pouzita iba raz, 2) neobsahuje ziadnu mega novu logiku iba vola tu inu vrstvu. Ja by som tieto vsetky metody dal normalne ako sucast tych materskych metod, len zaberaju zbytocne miesto, ale nevidim to ako nejako velku prioritu.

2021-04-27 13:52 UTC, ludko commented
Co sa tyka modelu, aj ten sa mi uz zacina pozdavat, len tam len budem este nieco pridavat ked budem robit ten dalsi servlet.

2021-04-27 13:52 UTC, ludko commented
Co sa tyka javascriptu tam som to rozmyslal este nasekat dajako, ale asi kaslat nato uz niejeto ani priorita a extra prehladnejsie by to aj tak nebolo.

2021-04-27 22:54 UTC, cergina commented on src/main/java/Control/Scenario/UC_ListBuilding.java
> +public class UC_ListBuilding {
Toto je holt vec osobneho vkusu, ale nebranim sa ak to tak vyhovuje viac.

2021-04-27 22:55 UTC, cergina commented on src/main/java/Model/Web/ControllerUnit.java
> +    public Integer uid;
tu sa Veronika len pytala davnejsie, ze ci tu musi byt public, ked uz su tu gettery

2021-04-27 22:57 UTC, cergina commented on src/main/java/View/Support/ServletHelper.java
> +        Integer requestedId = null;
Oukej, toto je zaujimave ak to  funguje

2021-04-27 23:01 UTC, cergina commented on src/main/java/View/Web/Servlets/Privileged/UserSpecific/CentralUnitInformationServlet.java
>              return;
akonahle spravis return tak je else zbytocny

2021-04-27 23:02 UTC, cergina commented on src/main/java/View/Web/Servlets/Privileged/UserSpecific/IndexServlet.java
> +        context.setVariable("Email", user.getEmail()); // TODO tu normalne setVariable user, a potom v template user.phone a pod.
iste, aj tak ako je to v TODO sa da

2021-04-27 23:05 UTC, cergina requested changes
Asi by som suhlasil len teda, by som poprosil pozriet sa este na veci, ktore som okomentoval + by som pockal az kym realne nemergneme to pridavanie bytov co caka v pull requeste a toto az potom mergneme, co otestujeme aj ci sa nerozbila funkcionalita.

2021-04-28 05:02 UTC, ludko commented on src/main/java/Control/Scenario/UC_ListBuilding.java
> +public class UC_ListBuilding {
vies o co mi islo, ze ked mas triedy v packagi tak budu pri sebe abecedne, uz konkretne meno mi nezalezi ake bude

2021-04-28 05:02 UTC, ludko commented on src/main/java/Model/Web/ControllerUnit.java
> +    public Integer uid;
public je pre thymeleaf, getter pre gson, 2 rozdielne veci

2021-04-28 05:04 UTC, ludko commented on src/main/java/View/Web/Servlets/Privileged/UserSpecific/CentralUnitInformationServlet.java
>              return;
what toto som ja ani nekodil co si komentoval

2021-04-28 05:04 UTC, ludko commented on src/main/java/View/Support/ServletHelper.java
> +        Integer requestedId = null;
pomocna metoda len, vsimol som si pattern ktory sme opakovali vov vela servletoch. Hej mohol som ju okomentovat

2021-04-28 14:38 UTC, xcipelova commented on src/main/java/Control/Scenario/UC_ListBuilding.java
> +public class UC_ListBuilding {
to je dobry napad, ze vsetky triedy na zobrazovanie budu pod sebou

2021-04-28 14:38 UTC, xcipelova commented on src/main/java/Model/Web/ControllerUnit.java
> +    public Integer uid;
to ma zaujimalo preco su tam gettery, ale ked pre gson tak ok

2021-04-28 14:38 UTC, xcipelova commented on src/main/java/View/Support/ServletHelper.java
> +        Integer requestedId = null;
na konci by bolo dobre vsetko zlozitejsie okomentovat :D mame minimum komentarov zatial

2021-04-28 16:24 UTC, ludko commented
konflikty vyriesene, po mergi treba este premenovat UC_CreateFlat -> UC_NewFlat

2021-04-28 21:02 UTC, merged