Adding a graph for a building
cergina/SecureDataCollector pull request #55
Opened 2021-05-01 22:46 UTC by xcipelova

2021-05-01 23:38 UTC, ludko commented on src/main/java/Control/Scenario/UC_Graph.java
> +        jsonResponse.setStatus(HttpServletResponse.SC_CREATED);
co sa tu vytvorilo ked davas 201 Created?

2021-05-01 23:38 UTC, ludko commented on src/main/java/Model/Web/thymeleaf/Building.java
> +public class Building {
akoze cele si to mala z nejakej starsej vetvy forknute lebo cely model sa odvtedy uz dost zmenil

2021-05-01 23:38 UTC, ludko commented on src/main/java/View/Web/Servlets/Privileged/UserSpecific/BuildingInformationServlet.java
> +@WebServlet(name = "BuildingInformationServlet", urlPatterns = BuildingInformationServlet.SERVLET_URL)
na 1 budovu existuje servlet, nechcela si len tam doplnit graf?

2021-05-01 23:38 UTC, ludko commented
neviem ci su to 2 rozne pull requesty alebo rovnaky lebo zmeny su dost podobne tak som zmateny

2021-05-02 07:50 UTC, cergina requested changes
treba to jednoducho spracovat v najnovsom mastrovi

2021-05-02 12:40 UTC, closed without merging